Frontend UI
UKP-SQuARE/square-core pull request #172
Opened 2022-05-05 05:41 UTC by SevenDaysDA

2022-05-06 11:58 UTC, timbmg commented
Thanks for the PR @SevenDaysDA!

I think having a mixed nav with items not having, and having items looks a little weird. @Rachneet suggested to put the Feedback and Github items all the way to the right (i.e. left of the sign in / username) and separate it with a `|` from the sing-in / username button. What do you think?

2022-05-06 12:04 UTC, timbmg requested changes

2022-05-06 12:04 UTC, timbmg commented on square-frontend/src/components/Footer.vue
> +        <li class="nav-item"><img :src="`${publicPath}tud_logo.png`" alt="TU Darmstadt" width="120" height="40" class="px-2"></li>
also i would increase the height; ~60 looked good to me. I think ideally the font size of the TU-DA logo matches the font-size of the rest of the footer.

2022-05-09 08:57 UTC, SevenDaysDA commented
Hi @timbmg ,I agree.
The mixed elements look a bit off.
I moved them to the right.

2022-05-09 08:58 UTC, SevenDaysDA commented on square-frontend/src/components/Footer.vue
> +        <li class="nav-item"><img :src="`${publicPath}tud_logo.png`" alt="TU Darmstadt" width="120" height="40" class="px-2"></li>
Done. 
Thank you for the review.

2022-05-11 06:59 UTC, merged