KGQA skill
UKP-SQuARE/square-core pull request #428
Opened 2023-02-06 11:43 UTC by HaishuoFang

# What does this PR do?

### KGQA skill
- model: a seq2seq BART model 
- Dataset: KQApro dataset
- Workflow:
    - Get the generated SPARQL from the model API.
    - Postprocess the generated SPARQL.
    - Query this SPARQL against KB from Virtuoso.
    - Get the answer. 

## Who can review?

Feel free to tag members/contributors who may be interested in your PR.

@HaritzPuerto @Rachneet @timbmg

2023-02-06 11:58 UTC, timbmg commented
Currently, we only copy the `skill.py` file into the image. It seems your skill requires some more files. Would it be possible to have it all in one file? Or else, you would need to change the [Dockerfile](https://github.com/UKP-SQuARE/square-core/blob/9eb74d69618c069518cba8d35c879f59cce7e2bc/skills/Dockerfile), particularly, [this line](https://github.com/UKP-SQuARE/square-core/blob/9eb74d69618c069518cba8d35c879f59cce7e2bc/skills/Dockerfile#L17)

2023-02-06 12:17 UTC, timbmg requested changes

2023-02-06 12:17 UTC, timbmg commented on skills/KQAPro-KGQA/readme.md
> +## Package
Is this file required to check-in to the main repo? Seems just like your development comments?:)

2023-02-06 13:28 UTC, HaishuoFang commented on config.yaml
> +  - name: KQAPro-KGQA
I already added it. `multiple-choice-metaqa` needs to add one i think. I will add it

2023-02-09 07:34 UTC, timbmg approved these changes

2023-02-09 07:34 UTC, timbmg commented
LGTM. If you like you can deploy to prod and check if it works as expected.

2023-02-21 15:12 UTC, merged